library(parallel)
library(doParallel)
library(igraph)

population <- 10
m <- 2

test <- net.barabasi.albert(population,m,detectCores(),TRUE)

draw.net(test)

metric.cluster.global(test)

histo.dist(test)


neighbors(test, 2)


#writing code to transform generated list into a matrix

#create an empty matrix

initial_matrix <- matrix(,population,population)

#writing the code to take the list generated by test and use it to populate the empty matrix
for(i in 1:population){
  connection_vector <- neighbors(test,i)
  for (j in 1: population) {
    ifelse(j %in% connection_vector, initial_matrix[i,j]<-1, initial_matrix[i,j]<-0)
  }
}

